Added description for some options, updated styles
CleanTalk/joomla3.x-4.x-antispam pull request #18
Opened 2023-04-20 04:54 UTC by ArtemAnoshin

2023-04-20 05:01 UTC, svfcode approved these changes

2023-04-20 07:44 UTC, Glomberg requested changes

2023-04-20 07:44 UTC, Glomberg commented on language/ru-RU/ru-RU.plg_system_cleantalkantispam.ini
Need to be translate to RU

2023-04-27 09:47 UTC, ArtemAnoshin commented on language/ru-RU/ru-RU.plg_system_cleantalkantispam.ini
Added

2023-04-28 05:47 UTC, Glomberg approved these changes

2023-04-28 12:56 UTC, alexandergull approved these changes

2023-05-02 08:17 UTC, merged