Fix. Cron. Added serve buttons to check cron.
CleanTalk/joomla3.x-4.x-antispam pull request #32
Opened 2023-12-28 05:32 UTC by svfcode

Task https://doboard.com/1/task/4874

2023-12-28 07:28 UTC, Glomberg requested changes

2023-12-28 07:28 UTC, Glomberg commented on cleantalkantispam.php
> +            if (isset($_POST['ct_serve_run_cron_sfw_send_logs']) && $_POST['ct_serve_run_cron_sfw_send_logs'] === 'yes') {
Please add CSRF checking here.

2023-12-28 07:28 UTC, Glomberg commented on cleantalkantispam.php
> +            if (isset($_POST['ct_serve_run_cron_sfw_update']) && $_POST['ct_serve_run_cron_sfw_update'] === 'yes') {
Please add CSRF checking here.

2024-01-16 06:15 UTC, svfcode commented on cleantalkantispam.php
> +            if (isset($_POST['ct_serve_run_cron_sfw_send_logs']) && $_POST['ct_serve_run_cron_sfw_send_logs'] === 'yes') {
Already checked here https://github.com/CleanTalk/joomla3.x-4.x-antispam/pull/32/files/617a7a0e2fc8ff303b9b7a487fb7f463a03c71b1#diff-da34647e4d084d8b926ed7ebeed639f9badd0c7632f411f2b50e3c77dc4f89b7R300.

2024-01-16 06:15 UTC, svfcode commented on cleantalkantispam.php
> +            if (isset($_POST['ct_serve_run_cron_sfw_update']) && $_POST['ct_serve_run_cron_sfw_update'] === 'yes') {
Already checked here https://github.com/CleanTalk/joomla3.x-4.x-antispam/pull/32/files/617a7a0e2fc8ff303b9b7a487fb7f463a03c71b1#diff-da34647e4d084d8b926ed7ebeed639f9badd0c7632f411f2b50e3c77dc4f89b7R300.

2024-01-16 06:24 UTC, Glomberg approved these changes

2024-01-16 07:43 UTC, alexandergull approved these changes

2024-01-16 10:04 UTC, merged